project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: tab-one/tab-one-index.qmd
        text: DMP
      - href: tab-iframe/iframe-index.qmd
        text: Questionnaire
      - href: tab-presentation/presentation-index.qmd
        text: Presentations        
      - href: tab-SurveyDataAnalysis/DataAnalysis-index.qmd
        text: Data Analysis
      - href: tab-dashboard/interactive-index.qmd
        text: Interactive Dashboard
      - href: tab-sentiment/analysis-index.qmd
        text: Sentiment Analysis
    logo: images/logo.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

