project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: tab-one/tab-one-index.qmd
        text: DMP
      - href: tab-presentation/presentation-index.qmd
        text: Presentations        
      - href: tab-iframe/iframe-index.qmd
        text: iFrame example
    logo: images/logo.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

